[package]
name = "ao-baker"
version = "0.1.0"
authors = ["petr"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
glium = "0.26.0-alpha6"
wavefront_obj = "7.0.0"
cgmath = "0.17.0"
rand = "0.7.2"
rusttype = "0.8"